using Gauniv.WebServer.Data;
using Gauniv.WebServer.Dtos;
using MapsterMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Gauniv.WebServer.Api
{
    [Route("api/1.0.0/[controller]/[action]")]
    [ApiController]
    public class AdminController(ApplicationDbContext appDbContext, IMapper mapper) : ControllerBase
    {
        private readonly ApplicationDbContext appDbContext = appDbContext;
        private readonly IMapper mapper = mapper;

        #region Game Management

        [HttpPost]
        public async Task<ActionResult<GameDto>> AddGame([FromBody] GameDto gameDto)
        {
            try
            {
                var local_game = mapper.Map<Game>(gameDto);
                local_game.Id = 0; // Ensure ID is generated by DB
                
                appDbContext.Games.Add(local_game);
                await appDbContext.SaveChangesAsync();

                return Ok(mapper.Map<GameDto>(local_game));
            }
            catch (Exception ex)
            {
                return StatusCode(500, $"Error adding game: {ex.Message}");
            }
        }

        [HttpPost]
        public async Task<ActionResult<GameDto>> UploadGame([FromForm] string title, [FromForm] string description, 
            [FromForm] decimal price, [FromForm] string? categories, [FromForm] IFormFile? executable)
        {
            try
            {
                if (string.IsNullOrWhiteSpace(title))
                    return BadRequest("Title is required");

                var local_game = new Game
                {
                    Title = title,
                    Description = description ?? "",
                    Price = price,
                    Categories = string.IsNullOrWhiteSpace(categories) 
                        ? new List<string>() 
                        : categories.Split(',').Select(c => c.Trim()).ToList()
                };

                // Upload executable if provided
                if (executable != null && executable.Length > 0)
                {
                    using var local_memoryStream = new MemoryStream();
                    await executable.CopyToAsync(local_memoryStream);
                    local_game.payload = local_memoryStream.ToArray();
                }

                appDbContext.Games.Add(local_game);
                await appDbContext.SaveChangesAsync();

                return Ok(mapper.Map<GameDto>(local_game));
            }
            catch (Exception ex)
            {
                return StatusCode(500, $"Error uploading game: {ex.Message}");
            }
        }

        [HttpPut("{id}")]
        public async Task<ActionResult<GameDto>> UpdateGame(int id, [FromBody] GameDto gameDto)
        {
            try
            {
                var local_game = await appDbContext.Games.FindAsync(id);
                if (local_game == null) return NotFound($"Game {id} not found");

                mapper.Map(gameDto, local_game);
                local_game.Id = id; // Ensure ID remains same

                await appDbContext.SaveChangesAsync();
                return Ok(mapper.Map<GameDto>(local_game));
            }
            catch (Exception ex)
            {
                return StatusCode(500, $"Error updating game: {ex.Message}");
            }
        }

        [HttpDelete("{id}")]
        public async Task<ActionResult> DeleteGame(int id)
        {
            try
            {
                var local_game = await appDbContext.Games.FindAsync(id);
                if (local_game == null) return NotFound($"Game {id} not found");

                appDbContext.Games.Remove(local_game);
                await appDbContext.SaveChangesAsync();
                return Ok(new { message = "Game deleted successfully" });
            }
            catch (Exception ex)
            {
                return StatusCode(500, $"Error deleting game: {ex.Message}");
            }
        }

        #endregion

        #region Category Management

        [HttpPost]
        public async Task<ActionResult<CategoryDto>> AddCategory([FromBody] CategoryDto categoryDto)
        {
            try
            {
                if (await appDbContext.Categories.AnyAsync(c => c.Name == categoryDto.Name))
                    return BadRequest("Category already exists");

                var local_category = new Category { Name = categoryDto.Name };
                appDbContext.Categories.Add(local_category);
                await appDbContext.SaveChangesAsync();

                return Ok(new CategoryDto { Id = local_category.Id, Name = local_category.Name });
            }
            catch (Exception ex)
            {
                return StatusCode(500, $"Error adding category: {ex.Message}");
            }
        }

        [HttpPut("{id}")]
        public async Task<ActionResult<CategoryDto>> UpdateCategory(int id, [FromBody] CategoryDto categoryDto)
        {
            try
            {
                var local_category = await appDbContext.Categories.FindAsync(id);
                if (local_category == null) return NotFound($"Category {id} not found");

                string local_oldName = local_category.Name;
                string local_newName = categoryDto.Name;

                if (local_oldName != local_newName)
                {
                    local_category.Name = local_newName;

                    // Update all games that use this category string
                    var local_gamesToUpdate = await appDbContext.Games
                        .Where(g => g.Categories.Contains(local_oldName))
                        .ToListAsync();

                    foreach (var local_game in local_gamesToUpdate)
                    {
                        var local_list = local_game.Categories.ToList();
                        int local_index = local_list.IndexOf(local_oldName);
                        if (local_index != -1)
                        {
                            local_list[local_index] = local_newName;
                            local_game.Categories = local_list;
                        }
                    }
                }

                await appDbContext.SaveChangesAsync();
                return Ok(new CategoryDto { Id = local_category.Id, Name = local_category.Name });
            }
            catch (Exception ex)
            {
                return StatusCode(500, $"Error updating category: {ex.Message}");
            }
        }

        [HttpDelete("{id}")]
        public async Task<ActionResult> DeleteCategory(int id)
        {
            try
            {
                var local_category = await appDbContext.Categories.FindAsync(id);
                if (local_category == null) return NotFound($"Category {id} not found");

                string local_catName = local_category.Name;

                // Remove category from all games
                var local_gamesToUpdate = await appDbContext.Games
                    .Where(g => g.Categories.Contains(local_catName))
                    .ToListAsync();

                foreach (var local_game in local_gamesToUpdate)
                {
                    var local_list = local_game.Categories.ToList();
                    local_list.Remove(local_catName);
                    local_game.Categories = local_list;
                }

                appDbContext.Categories.Remove(local_category);
                await appDbContext.SaveChangesAsync();
                return Ok(new { message = "Category deleted successfully" });
            }
            catch (Exception ex)
            {
                return StatusCode(500, $"Error deleting category: {ex.Message}");
            }
        }

        #endregion
    }
}
